import { DRAFT, type Mission } from "./types";

// Facts, scale numbers, roles and dates come only from PROFILE.md.
// Framing and phrasing are editorial. Anything that would require a metric,
// outcome or research finding Ali has not confirmed is left as DRAFT.

export const missions: Mission[] = [
  {
    slug: "technician-app",
    title: "Technician App",
    org: "MapMyIndia [Gtropy]",
    role: "Frontend · UI/UX · PRD · cross-functional delivery",
    period: "Active",
    status: "active",
    featured: true,
    premise:
      "Field operations run on people who are never at a desk. The app had to work the way a technician's day actually works.",
    stack: ["Angular", "Ionic", "TypeScript", "REST APIs"],
    signals: [{ label: "Stage", value: "Building end to end" }],
    report: [
      {
        label: "Brief",
        body: "An end-to-end app for tracking technicians and managing field operations — installation, replacement and rectification jobs — built end to end.",
      },
      {
        label: "Context",
        body: "Installation, replacement and rectification are three different jobs wearing the same uniform. Each has its own preconditions, its own proof-of-completion, and its own way of going wrong once someone is standing at a vehicle with a phone in one hand.",
      },
      { label: "Users", body: "Field technicians and the operations staff who dispatch and verify their work." },
      { label: "Discovery", body: DRAFT },
      {
        label: "Problem",
        body: "Coordination lived in messages and spreadsheets. Nobody could answer where a job stood without asking a person.",
      },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      {
        label: "UX",
        body: "Designed for one hand, poor signal and bright daylight. Job state is the first thing on screen, not the last.",
      },
      { label: "Design", body: DRAFT },
      { label: "Technology", body: "Angular and Ionic for a single cross-platform build against the existing platform APIs." },
      { label: "Build", body: "In progress. Ali owns frontend implementation, UI/UX, the PRD, and coordination across the teams involved." },
      { label: "Outcome", body: `${DRAFT} — time saved, error rate and adoption are not yet measured.` },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "mappls-shop-admin",
    title: "Mappls Shop Admin & Automated Billing",
    org: "MapMyIndia [Gtropy]",
    role: "UI/UX owner · PRD author · cross-functional delivery",
    period: "Active",
    status: "active",
    featured: true,
    premise:
      "Billing was done by hand. The interesting part was not automating the maths — it was finding every place a human was quietly making a decision.",
    stack: ["React", "TypeScript", "REST APIs"],
    signals: [{ label: "Replaces", value: "A fully manual billing process" }],
    report: [
      {
        label: "Brief",
        body: "Replace a fully manual billing process with an automated system, and give shop operations a first-class admin surface.",
      },
      {
        label: "Context",
        body: "A manual process is never only arithmetic. It carries exceptions, tolerances and judgement calls that were never written down anywhere, because the person doing them never needed them written down.",
      },
      { label: "Users", body: "Shop administrators and the billing operations team." },
      { label: "Discovery", body: DRAFT },
      {
        label: "Problem",
        body: "Manual billing is slow, and it is inconsistent in ways that only surface at reconciliation time.",
      },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: DRAFT },
      { label: "Design", body: DRAFT },
      { label: "Technology", body: DRAFT },
      { label: "Build", body: "Ali owns the UI/UX, wrote the PRD, and drives delivery across the teams involved." },
      { label: "Outcome", body: `${DRAFT} — outcome metrics are not yet measured.` },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "iocl-geortd",
    title: "IOCL GeoRTD Pipeline",
    org: "MapMyIndia [Gtropy]",
    role: "Frontend · UI/UX · cross-functional delivery",
    period: "Active",
    status: "active",
    featured: true,
    premise:
      "Thirty thousand routes is not a data problem you solve once. It is a pipeline you have to trust every time it runs.",
    stack: ["Geospatial data", "Amazon S3", "TypeScript"],
    signals: [{ label: "Routes injected", value: "30,000+" }],
    report: [
      { label: "Brief", body: "Geospatial route data creation for Indian Oil — GeoRTD generation at scale." },
      { label: "Context", body: DRAFT },
      { label: "Users", body: DRAFT },
      { label: "Discovery", body: DRAFT },
      { label: "Problem", body: DRAFT },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: DRAFT },
      { label: "Design", body: DRAFT },
      { label: "Technology", body: "Route data generated and injected into an Amazon S3 bucket — 30,000+ routes." },
      { label: "Build", body: "In progress." },
      { label: "Outcome", body: `${DRAFT} — outcome metrics are not yet measured.` },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "vahan-shakti",
    title: "Vahan Shakti",
    org: "MapMyIndia [Gtropy]",
    role: "Frontend · map UX",
    period: "Shipped",
    status: "shipped",
    featured: true,
    premise:
      "The challenge was never drawing the vehicles. It was keeping the map useful once thousands of them were moving at the same time.",
    stack: ["React", "Mappls SDK", "TypeScript", "RxJS"],
    signals: [
      { label: "Users", value: "200,000+" },
      { label: "Distribution", value: "Live on Play Store" },
      { label: "Sector", value: "Government" },
    ],
    report: [
      { label: "Brief", body: "Vehicle tracking and analytics for a government fleet programme." },
      {
        label: "Context",
        body: "A map that shows everything shows nothing. Past a certain density, every additional marker removes information rather than adding it.",
      },
      { label: "Users", body: "Government fleet operators and administrators — 200,000+ of them." },
      { label: "Discovery", body: DRAFT },
      {
        label: "Problem",
        body: "Live location at national scale, rendered in a browser, without the interface collapsing into noise.",
      },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      {
        label: "UX",
        body: "Clustering and heatmaps carry density; custom markers and plotted routes carry the individual case. The map changes what it emphasises as you zoom, so the answer stays legible at every altitude.",
      },
      { label: "Design", body: DRAFT },
      {
        label: "Technology",
        body: "React map components over the Mappls SDK — live location, custom markers, route plotting, clustering and heatmaps.",
      },
      { label: "Build", body: DRAFT },
      { label: "Outcome", body: "Live on the Play Store, serving 200,000+ users." },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "intouch",
    title: "Intouch",
    org: "MapMyIndia [Gtropy]",
    role: "Frontend · performance",
    period: "Shipped",
    status: "shipped",
    featured: true,
    premise:
      "Built for ten thousand vehicles, architected for fifty thousand — because the second number is the one that arrives without warning.",
    stack: ["React", "Ionic", "TypeScript", "RxJS"],
    signals: [
      { label: "Active vehicles", value: "10,000+" },
      { label: "Headroom", value: "Scaling to 50,000" },
      { label: "Distribution", value: "Live on Play Store" },
    ],
    report: [
      { label: "Brief", body: "A cross-platform logistics management app for fleet operators." },
      { label: "Context", body: DRAFT },
      { label: "Users", body: "Logistics and fleet operations teams." },
      { label: "Discovery", body: DRAFT },
      {
        label: "Problem",
        body: "Optimising for the fleet you have today produces an app that breaks on the fleet you have next quarter.",
      },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: DRAFT },
      { label: "Design", body: DRAFT },
      { label: "Technology", body: "Cross-platform build, optimised for 10,000+ active vehicles with a path to 50,000." },
      { label: "Build", body: DRAFT },
      { label: "Outcome", body: "Live on the Play Store." },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "locate",
    title: "Locate — Manufacturer Backend",
    org: "MapMyIndia [Gtropy]",
    role: "Frontend lead (independent)",
    period: "Shipped",
    status: "shipped",
    premise:
      "Twenty thousand vehicles across one state, watched from both a desk and a phone. The two screens needed the same truth, not the same layout.",
    stack: ["React", "TypeScript", "Mappls SDK"],
    signals: [
      { label: "Vehicles", value: "20,000+" },
      { label: "Coverage", value: "Maharashtra" },
    ],
    report: [
      { label: "Brief", body: "Real-time vehicle monitoring for an OEM — web and mobile dashboards." },
      { label: "Context", body: DRAFT },
      { label: "Users", body: "Manufacturer operations teams monitoring 20,000+ vehicles across Maharashtra." },
      { label: "Discovery", body: DRAFT },
      { label: "Problem", body: DRAFT },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: DRAFT },
      { label: "Design", body: DRAFT },
      { label: "Technology", body: "Web and mobile dashboards over real-time vehicle telemetry." },
      { label: "Build", body: "Ali independently led the frontend." },
      { label: "Outcome", body: DRAFT },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "control-tower",
    title: "Control Tower",
    org: "MapMyIndia [Gtropy]",
    role: "Frontend · dashboard architecture",
    period: "Shipped",
    status: "shipped",
    premise:
      "The system knew everything. It just didn't know what mattered first.",
    stack: ["React", "TypeScript", "RxJS", "Mappls SDK"],
    signals: [{ label: "Domain", value: "Alerts & ticketing" }],
    report: [
      { label: "Brief", body: "A real-time alert management and ticketing platform with map-based trip analysis." },
      {
        label: "Context",
        body: "An alert that fires constantly stops being an alert. It becomes background noise with a red icon.",
      },
      { label: "Users", body: DRAFT },
      { label: "Discovery", body: DRAFT },
      { label: "Problem", body: "Turning a continuous stream of vehicle events into a queue a human can actually work through." },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: DRAFT },
      { label: "Design", body: DRAFT },
      { label: "Technology", body: "Performance-optimised architecture; map-based trip analysis." },
      { label: "Build", body: DRAFT },
      { label: "Outcome", body: DRAFT },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "indane-yatra-mitra",
    title: "Indane Yatra Mitra",
    org: "MapMyIndia [Gtropy] · for IOCL",
    role: "Frontend · UI/UX",
    period: "Shipped",
    status: "shipped",
    premise:
      "When the cargo is LPG, a tracking product stops being a logistics tool and starts being a safety one.",
    stack: ["React", "Ionic", "Mappls SDK", "TypeScript"],
    signals: [{ label: "Distribution", value: "Live on Play Store" }],
    report: [
      { label: "Brief", body: "Enterprise fleet tracking for IOCL LPG tanker operations." },
      { label: "Context", body: DRAFT },
      { label: "Users", body: DRAFT },
      { label: "Discovery", body: DRAFT },
      { label: "Problem", body: DRAFT },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: "Route playback and role-based access, so each role sees the slice of the fleet it is accountable for." },
      { label: "Design", body: DRAFT },
      {
        label: "Technology",
        body: "Live tracking, safety alarms, geofencing, route playback and role-based access control.",
      },
      { label: "Build", body: DRAFT },
      { label: "Outcome", body: "Live on the Play Store." },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "fastag-platform",
    title: "FASTag Platform",
    org: "MapMyIndia [Gtropy]",
    role: "Full stack",
    period: "Shipped",
    status: "shipped",
    premise:
      "Registration flows are where products lose people. Multi-vehicle registration is where they lose them twice.",
    stack: ["React", "Node.js", "REST APIs"],
    signals: [{ label: "Scope", value: "Full stack" }],
    report: [
      { label: "Brief", body: "Full-stack FASTag registration with multi-vehicle management and OTP authentication." },
      { label: "Context", body: DRAFT },
      { label: "Users", body: DRAFT },
      { label: "Discovery", body: DRAFT },
      { label: "Problem", body: DRAFT },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: DRAFT },
      { label: "Design", body: DRAFT },
      { label: "Technology", body: "OTP authentication, multi-vehicle management, full-stack implementation." },
      { label: "Build", body: DRAFT },
      { label: "Outcome", body: DRAFT },
      { label: "Learnings", body: DRAFT },
    ],
  },
  {
    slug: "hermes",
    title: "Hermes",
    org: "MapMyIndia [Gtropy]",
    role: "Frontend · design system",
    period: "Shipped",
    status: "shipped",
    premise:
      "Internal tools get judged by the people who have no choice but to use them. That is a harder audience, not an easier one.",
    stack: ["React", "TypeScript"],
    signals: [{ label: "Audience", value: "Internal" }],
    report: [
      { label: "Brief", body: "An internal logistics and data management tool." },
      { label: "Context", body: DRAFT },
      { label: "Users", body: "Internal operations staff." },
      { label: "Discovery", body: DRAFT },
      { label: "Problem", body: DRAFT },
      { label: "Hypothesis", body: DRAFT },
      { label: "Strategy", body: DRAFT },
      { label: "Prioritization", body: DRAFT },
      { label: "UX", body: "Accessibility was treated as a requirement, not a pass at the end." },
      { label: "Design", body: "Modular, component-driven UI." },
      { label: "Technology", body: DRAFT },
      { label: "Build", body: DRAFT },
      { label: "Outcome", body: DRAFT },
      { label: "Learnings", body: DRAFT },
    ],
  },
];

export const featuredMissions = missions.filter((m) => m.featured);
export const activeMissions = missions.filter((m) => m.status === "active");

export function getMission(slug: string) {
  return missions.find((m) => m.slug === slug);
}
