/*
 * Writing (2026-09-20): every piece Ali has published, in one log. Titles,
 * outlets and dates are transcribed from the Medium RSS feed
 * (medium.com/feed/@aliazamkazmi1291, read 2026-09-20) and dumbmoney.in;
 * each `line` is a one-sentence description of what the piece is about,
 * taken from its own opening — no claims about reach or reception.
 */
export type Piece = {
  title: string;
  /** "Space OS" = written and hosted here (/writing/<slug>); the others link out. */
  outlet: "Medium" | "DumbMoney" | "Space OS";
  /** ISO date. */
  date: string;
  href: string;
  /** Hosted pieces only: the route, the paragraphs ("## " prefixes a subhead), and whether it is live. A draft renders in development only. */
  slug?: string;
  body?: string[];
  status?: "draft" | "published";
  line: string;
  kind: "case study" | "essay" | "guide";
  /** Where on this site the piece connects — the venture, a case study, the deck. Only real relations. */
  related?: { label: string; href: string };
  /** Hosted pieces: the searches the piece is written to answer. Lead the page's keywords and its JSON-LD. */
  keywords?: string[];
};

export const writing: Piece[] = [
  /*
   * The two guides (2026-10-01). Ali: "add and post blogs on ai agents we can
   * use like library, use seo keywords, write a good humanised blog." Read
   * both ways: a library of agents to USE, and the frameworks you import
   * like a library to BUILD one. Every product fact was checked on the day
   * of writing (dates, plans, licences), because this shelf changes monthly;
   * nothing claims Ali uses a given tool, since PROFILE.md does not say so.
   */
  {
    title: "AI agents you can use today, sorted by job",
    outlet: "Space OS",
    date: "2026-10-01",
    slug: "ai-agents-you-can-use",
    href: "/writing/ai-agents-you-can-use",
    status: "published",
    kind: "guide",
    line: "The AI agents worth using in 2026, sorted by the job they do, with what each is good for and how I'd choose between them.",
    related: { label: "Before you hand one permissions: the alarm problem", href: "/writing/agents-and-the-alarm-problem" },
    keywords: [
      "AI agents you can use",
      "best AI agents 2026",
      "list of AI agents",
      "AI agent tools",
      "AI coding agents",
      "AI browser agents",
      "AI agents for office work",
      "AI agents for customer support",
      "self-hosted AI agent",
      "AI agents for product managers",
    ],
    body: [
      "“Agent” now covers almost anything with a model inside it. The autocomplete in your editor is sold as one, and so is the assistant that opens a browser, signs in to your accounts and books the flight. Asking which agent is best is like asking which vehicle is best. I have spent two years building fleet software, and the first question there is always what you are carrying.",
      "So this is a library, shelved by the job rather than the brand. For each agent: what it is good at, where I would put it to work and what I would keep an eye on. It is a snapshot of the start of October 2026, and the shelves move fast. OpenAI alone shipped three different kinds of agent inside ChatGPT this year, and in June it announced that Agent Builder, the visual canvas it launched in October 2025, will stop working on 30 November. Choose the job first. The product name is the part most likely to change.",
      "If you want agents to build rather than to use, the companion piece is [a guide to the agent frameworks you can import like a library](/writing/ai-agent-frameworks).",
      "## Two questions to ask of any of them",
      "First, what can it touch? An agent that drafts is making a suggestion. One that sends, merges or pays is taking an action, and those deserve different permissions. Second, what happens the tenth time it gets something wrong: who notices, and how do they undo it? I have written about this as [the alarm problem](/writing/agents-and-the-alarm-problem), and every entry below is easier to judge with both questions in mind.",
      "## AI coding agents",
      "The most crowded shelf, and the most mature. The honest way to divide it is by where you want to supervise the work: in the terminal, in the editor or in a pull request.",
      "### Claude Code",
      "Anthropic's agent began in the terminal and now runs in editors, the desktop app and the browser too. It reads the repository, runs commands, edits files and checks its work against your tests, and it is strongest on a change that spans many files in a codebase it can explore. Watch the permissions. It acts with whatever access the person running it has, so the list of commands you allow is a product decision, not a setting. Its loop is also published as a library, which the [framework guide](/writing/ai-agent-frameworks) covers.",
      "### OpenAI Codex",
      "OpenAI's coding agent works in the cloud as well as in a terminal and an editor. Its natural rhythm is the background job: you hand over a task, it works in a sandbox and comes back with a change to review. That suits a backlog of well-described tickets far better than a design problem nobody has written down yet. The [Codex CLI](https://github.com/openai/codex) is open source, if you want to see how the loop is put together.",
      "### GitHub Copilot",
      "If your team already lives in GitHub, Copilot's coding agent removes a step rather than adding a tool. Assign it an issue and it opens a pull request, which goes through the same review as anyone else's. That makes for a duller demo and a better fit for an organisation, because nothing about the workflow changes except who wrote the first draft.",
      "### Cursor",
      "An editor built around the model, for people who want to watch each step and steer as it goes. If your instinct is to read a diff while it is being written rather than afterwards, start here.",
      "The comparisons published this year disagree about which of these writes the best code, and the disagreements tend to follow whoever ran the test. What does not change is the bill on the other side: [the generated code still has to be reviewed](/writing/the-bottleneck-moved), and review is where the time goes now.",
      "## AI agents for office work",
      "This is the shelf most people outside engineering will actually use. These agents work through documents, spreadsheets, inboxes and folders, and come back with something finished rather than a reply.",
      "### ChatGPT: Work, workspace agents and dots",
      "OpenAI now has three shapes of agent inside ChatGPT, launched within six months of each other. Workspace agents (April) are shared agents a team builds once, connects to tools such as Slack and Salesforce and lets run in the cloud, with approval steps where they matter; for companies they replace custom GPTs. ChatGPT Work (9 July) takes an outcome rather than a prompt and works for hours towards a finished spreadsheet, deck or document. Dots, announced at DevDay on 29 September and still rolling out, are always-on agents with a computer of their own in the cloud, which you can message from ChatGPT, Slack or Teams.",
      "Which one to reach for follows from the job. A recurring team process is a workspace agent. A one-off piece of work with a clear finish line is Work. Something you want watched continuously is what dots are for, and it is the one I would introduce most carefully, because an agent that never stops is an alarm that never stops.",
      "### Claude",
      "Anthropic took the Claude Code idea to people who will never open a terminal. It started in January as Cowork, a separate mode where you handed Claude a folder and a multi-step job. Since 16 September it has simply been part of the Claude app: you describe what you want, and Claude decides whether that needs an answer or a piece of work. It can work on your files and inside connected apps such as Gmail, Google Drive and Slack, and the merged version is reaching Pro and Max subscribers first.",
      "### Microsoft 365 Copilot and Gemini Enterprise",
      "If your company runs on Microsoft 365 or Google Workspace, the agent already inside your tenancy has one advantage none of the others can match: it has passed your security review. A slightly better agent that needs six months of procurement is, for most teams, a worse agent.",
      "## AI browser agents",
      "These drive a web browser the way you would: click, type, scroll, fill in the form. ChatGPT's agent mode does it inside ChatGPT (OpenAI has been folding its Atlas browser back into ChatGPT itself), Anthropic's Claude in Chrome does it from an extension, and Perplexity built an entire browser, Comet, around the idea.",
      "They are the most impressive to watch and the easiest to get into trouble with. A browser agent reads every page it visits, and a page can carry instructions written for the agent rather than for you. That is prompt injection, and no vendor claims to have solved it. My rule here is simple: begin with tasks that only read, keep it away from anything that pays, and sign it out of every account the task does not need.",
      "## AI research agents",
      "The deep research modes in ChatGPT, Gemini, Claude and Perplexity read dozens of sources and come back with a cited report. For a first pass at a market, a competitor set or a technical question, they turn an afternoon of open tabs into a few minutes of waiting.",
      "Read the citations, though. These tools sound equally sure whether a source says the thing or merely sits near it. Treat the report as a reading list with a draft attached, not as an answer.",
      "## AI agents for customer support",
      "Support is where agents have been in production longest, because the job is narrow and the outcome is countable. Intercom's Fin, Sierra and Decagon are built for it, and Salesforce's Agentforce is the natural pick if your support already runs on Salesforce.",
      "Vendors will quote a deflection rate. Ask for the resolution rate instead, and ask what happens at the handoff. A conversation the agent cannot finish should reach a person with the history attached, the way a fleet alarm should become a ticket with an owner. A customer who is deflected here and comes back angry through another channel has not been helped. They have been moved.",
      "## AI agents you host yourself",
      "### OpenClaw",
      "The open-source personal agent that took over developer feeds this year. It runs on your own machine or server, lives in the messaging apps you already use (WhatsApp, Telegram, Slack, Discord) and works on a schedule, watching sites, sorting email and running scripts while you sleep. [OpenClaw](https://github.com/openclaw/openclaw) is MIT-licensed and governed by a foundation; its creator joined OpenAI in February, and the project stayed independent.",
      "It is also the clearest example of the trade every agent here asks of you. It can do a great deal because you give it a great deal: your shell and your files, and often your accounts. Its skills are folders of instructions and scripts that anyone can publish, so installing one means running somebody else's code. Keep it on a machine that holds nothing you would mind losing until you have read what you installed.",
      "### n8n",
      "When the job is a pipeline rather than a conversation, a workflow tool with agent steps is often the better build. [The n8n workflow tool](https://n8n.io) can be self-hosted, and its agent node lets a model make the decisions inside a flow you can see, test and version. The flow is the part that survives when you swap the model.",
      "## How I would choose",
      "Start from where the work ends up and who signs it off. Code ends in a pull request, so choose an agent that delivers to one. A report ends with a manager, so choose the one that lives where that manager already reads.",
      "Then set the autonomy per action, not per product. A draft is cheap to undo. A sent email is not, and a payment is worse. Most of these tools now let you require approval for some actions and not others; use that, and loosen it only when you have evidence that it is safe to.",
      "And keep your work portable. The instructions you give an agent can live in plain files: [Agent Skills](https://agentskills.io), the SKILL.md format Anthropic released as an open standard, is now read by Claude Code, Codex, Copilot and Cursor alike. Your connections to other systems can go through the [Model Context Protocol](https://modelcontextprotocol.io), which the Linux Foundation now looks after. Agent Builder's users have until 30 November to rebuild, and the ones who kept their logic outside the canvas will have the easier month.",
      "## What I would measure",
      "Not how often people open it. How many of its actions a person reversed. How many of its drafts went out without an edit. How long a task took with it compared with the same task without it, measured rather than felt. And the number that tells you whether trust is growing or quietly leaking away: how many permissions people still allow it after three months, compared with the first week.",
    ],
  },
  {
    title: "AI agent frameworks to use like a library",
    outlet: "Space OS",
    date: "2026-10-01",
    slug: "ai-agent-frameworks",
    href: "/writing/ai-agent-frameworks",
    status: "published",
    kind: "guide",
    line: "The agent SDKs worth importing in 2026, from OpenAI, Anthropic and Google to LangGraph, CrewAI and Mastra, and how to pick one.",
    related: { label: "Write this first: a PRD for a feature that can be wrong", href: "/writing/prd-for-an-ai-feature" },
    keywords: [
      "AI agent frameworks",
      "best AI agent framework 2026",
      "AI agent SDK",
      "OpenAI Agents SDK",
      "Claude Agent SDK",
      "Google Agent Development Kit",
      "Microsoft Agent Framework",
      "LangGraph vs CrewAI",
      "TypeScript AI agent framework",
      "Model Context Protocol",
    ],
    body: [
      "Strip any AI agent down and you find a loop. You send the model a goal and a list of tools. It asks for a tool, you run it and send back the result, and round it goes until the model says it is done. You can write that in an afternoon.",
      "The frameworks exist for everything around the loop: keeping state when a run lasts an hour, retrying the step that failed without repeating the ones that worked, pausing for a person to approve something, remembering across sessions, and recording what happened so you can work out why it went wrong. That is the part worth importing, and it is why choosing a framework is a product decision as much as an engineering one.",
      "There is a second distinction this year has made expensive. A library is code you own that calls a vendor. A platform is a vendor that holds your logic. Agent Builder, the visual canvas OpenAI launched in October 2025, stops working on 30 November 2026, and OpenAI's own advice to the people who built on it is to rebuild in code. Everything below is something you import, and that is the point of the list. If you want agents to use rather than to build, start with [the library of ready-made ones](/writing/ai-agents-you-can-use).",
      "## The vendor SDKs",
      "Each of the big model companies now ships two things: an open-source library for the loop, and a hosted service that runs agents for you. The libraries are the shortest path once you have chosen a model, and the most opinionated about which model that is.",
      "### OpenAI Agents SDK",
      "Open source, in Python and TypeScript, with a deliberately small surface: agents, tools, handoffs between agents, guardrails and tracing. It is where OpenAI points everyone leaving Agent Builder. The small surface is the selling point. You write more of the plumbing yourself than with the heavier frameworks, and you understand all of it. The hosted counterpart arrived at DevDay on 29 September as an Agents API in public beta, with hosted execution, memory and computer use. [The SDK itself](https://github.com/openai/openai-agents-python) is a short read.",
      "### Claude Agent SDK",
      "Anthropic took the loop that runs Claude Code and published it as a library for Python and TypeScript. File access, shell commands and web search come built in, along with the context management that stops a long task drowning in its own history. It is strongest when your agent's job looks like a developer's: read things, run things, check the result. If you would rather not run the sandbox yourself, Claude Managed Agents, in public beta since April, hosts it for you. The [Python package](https://github.com/anthropics/claude-agent-sdk-python) is the place to start.",
      "### Google Agent Development Kit",
      "Google's ADK comes in Python, Java, Go and TypeScript, the widest spread of any kit here. Version 2.0, generally available for Python since May, added a graph-based workflow runtime, so the same kit covers a simple tool-calling agent and a multi-step process with branches. It runs anywhere, and it is most at home on Google Cloud. [ADK for Python](https://github.com/google/adk-python) is the reference version the others follow.",
      "### Microsoft Agent Framework",
      "Microsoft merged AutoGen and Semantic Kernel into one framework and shipped it as 1.0 in April, for .NET and Python. Both predecessors are now in maintenance mode, so if you have a project on either, this is your migration. For a .NET team it is the obvious default, and on Azure the hosting comes with it: Foundry's hosted agents reached general availability in August. [One repository](https://github.com/microsoft/agent-framework) holds both languages.",
      "## The independent frameworks",
      "These work with any model, which matters more than it sounds. The model that is best for your task this quarter is unlikely to be the best one next year, and an independent framework turns that switch into a line of configuration.",
      "### LangGraph",
      "[LangGraph](https://github.com/langchain-ai/langgraph) is the most widely proven option for agents whose work has a shape. You draw the process as a graph of steps with explicit state, and in return you get durable execution, pauses for human approval and the ability to replay a run that broke. It reached 1.0 in October 2025 alongside LangChain 1.0, whose new agent builder, create_agent, runs on LangGraph underneath, and Uber, LinkedIn and Klarna are among its published users. The cost is that you have to think in graphs, which is the right cost if your process really does branch.",
      "### CrewAI",
      "[CrewAI](https://github.com/crewAIInc/crewAI) models a crew with roles (a researcher, a writer, a reviewer), each with its own goal. It is the quickest route from an idea to a multi-agent demo, often a few dozen lines of Python, and its Flows add the explicit control a demo leaves out. Be honest about whether your problem needs several agents at all. One agent with good tools usually beats three agents passing notes.",
      "### Pydantic AI",
      "[From the team behind Pydantic](https://github.com/pydantic/pydantic-ai), for people who like their contracts typed: typed inputs, typed tools and typed outputs, validated at the edges. If your agent's output feeds another system rather than a person, that checking is worth more than any feature list.",
      "### smolagents",
      "[Hugging Face's library](https://github.com/huggingface/smolagents) is small on purpose, and its agents act by writing and running Python rather than calling one tool at a time. For data work, such as loading a file, filtering it and plotting the result, that is quicker and easier to follow. Run it in a sandbox, because the agent is, by design, writing code you have not read.",
      "### Strands Agents",
      "[AWS's open-source SDK](https://github.com/strands-agents/sdk-python) lets the model drive the loop and ships with OpenTelemetry tracing built in. It works with several model providers, and it is the natural choice if you already deploy on AWS.",
      "## For TypeScript teams",
      "Most agent tutorials assume Python. If your product is a Next.js app, as this site is, two options fit better.",
      "### Vercel AI SDK",
      "Version 6 of [the AI SDK](https://github.com/vercel/ai) added an Agent abstraction: define the model, instructions and tools once, then use the agent anywhere in the app. Its real strength is everything around the agent on screen, from streaming responses to tool calls rendered as interface. Use it when the agent lives inside a product screen.",
      "### Mastra",
      "[Mastra](https://github.com/mastra-ai/mastra) reached 1.0 in January 2026 and bundles agents, workflows, memory, evaluations and a local studio for watching runs, all in TypeScript. A common pairing is the AI SDK underneath for the model calls and Mastra on top for the orchestration.",
      "## The protocols matter more than the framework",
      "The most useful thing to happen to agents in the past year is not a framework. It is a small set of open standards that let you change frameworks without rewriting everything you connected to them.",
      "The [Model Context Protocol](https://modelcontextprotocol.io), MCP, is how an agent reaches tools and data. Anthropic introduced it in November 2024 and handed it to the Linux Foundation's new Agentic AI Foundation in December 2025, and every framework above can use MCP tools. A2A, [Google's agent-to-agent protocol](https://a2a-protocol.org), covers agents talking to other agents and has sat with the Linux Foundation since June 2025. [Agent Skills](https://agentskills.io) packages instructions and scripts as folders with a SKILL.md file that any compatible agent can load.",
      "If your integrations are MCP servers and your know-how lives in skill files, the framework becomes the replaceable part. That is where you want to be when the next shutdown notice arrives.",
      "## How I would choose",
      "Five questions, in the order I would ask them.",
      "### Which model are you betting on, and how sure are you?",
      "Sure, and staying: the vendor's own SDK is the shortest path. Not sure, or planning to compare: an independent framework, so the model is a setting rather than a rewrite.",
      "### Is the work a loop or a process?",
      "One agent working until a goal is met needs very little, and a vendor SDK or Pydantic AI is plenty. Work with branches, approvals and steps that must not run twice needs a graph, from LangGraph, ADK 2.0's workflows or Microsoft's orchestration.",
      "### What does the rest of your product run on?",
      "Use the language your team already ships. TypeScript points to the AI SDK and Mastra, .NET to Microsoft Agent Framework, and Python to almost everything else. An agent written in a language nobody on call can read is a problem at three in the morning.",
      "### Where will it run, and who answers when it fails?",
      "Every big vendor now offers to host your agent: OpenAI's Agents API, Claude Managed Agents, Foundry's hosted agents. That is a sensible trade for a first version, provided you know what it would take to leave.",
      "### What happens when it is wrong?",
      "Check that pausing for a person is built in rather than bolted on. LangGraph's interrupts, LangChain's human-in-the-loop middleware and the approval hooks in the vendor SDKs all exist for this. The [PRD for a feature that can be wrong](/writing/prd-for-an-ai-feature) gets written before the framework is chosen, and it should settle this question.",
      "## What I would measure",
      "Not stars or downloads, which measure marketing. The time from an empty repository to the first useful run, and the time to the first failure you could not explain from the traces. The share of runs that needed a person. Cost per task that actually succeeded, rather than per call. And the portability tax: how much code you would have to rewrite to change framework next year. If that number frightens you, the framework is holding more of your product than it should.",
    ],
  },
  {
    title: "AI writes the code. The bottleneck moved.",
    outlet: "Space OS",
    date: "2026-09-23",
    slug: "the-bottleneck-moved",
    href: "/writing/the-bottleneck-moved",
    status: "published",
    kind: "essay",
    line: "Generation got cheap this year. Review did not, and knowing what to build got no cheaper at all. What that does to a team, from someone who writes the document and then builds it.",
    related: { label: "The teardown this one leans on", href: "/field-notes/ai-code-assistant-adoption-paradox" },
    body: [
      "Something changed in engineering this year and most of the reporting on it buried the interesting half. Yes, a large and growing share of committed code is now written with AI assistance. Yes, individual output is up sharply. The part worth paying attention to is that plenty of those teams are not shipping any faster, and some are shipping slower.",
      "The reports I have read this year all describe the same shape. Time to open a pull request falls. Time for that pull request to get merged rises, in some measurements by a lot. More code, arriving quicker, sitting longer.",
      "## The constraint moved and nobody moved with it",
      "Writing code used to be the expensive step. Everything around how teams work was built for that assumption: sprint sizing, estimates, the whole idea that engineering capacity is the thing you are short of.",
      "Generation got cheap. Reviewing did not. Somebody still has to read the diff and decide whether it is safe, whether it does what was actually wanted, and whether it introduced a problem that will surface in three months.",
      "And there is a second thing that got no cheaper at all, which is knowing what should have been built in the first place.",
      "## I can see it in my own week",
      "I write the PRD and then I am one of the people who builds it. That has always been two jobs with different rhythms, and until recently they took roughly comparable effort.",
      "The build half is faster now. Genuinely faster, not marginally. The document half is exactly as slow as it was, because none of the hard parts of it are typing. Working out which five words describe the states a vehicle can be in. Deciding whether the alarm should fire at four hours or at two. Sitting with the operations team until you understand why they do the thing that looks irrational on the dashboard.",
      "No assistant shortens that. It can draft you a PRD in nine seconds, and the draft will confidently pick four hours because four is a round number.",
      "## Review is where trust gets spent",
      "In a teardown I wrote earlier, the pattern with AI coding assistants was that developers adopt them, then quietly stop trusting them for anything load-bearing while carrying on using them for boilerplate. Nobody announces that. It shows up as a suggestion accepted at a lower rate and a review that takes longer than it used to.",
      "That is the bottleneck in one sentence. The generated code is plausible, which is precisely what makes it expensive to check. A reviewer cannot skim something that looks right and is sometimes wrong in a subtle place. They have to actually read it.",
      "I have argued before that at fleet scale, performance was a UX decision. This is the same species of argument. Review throughput is now a product delivery decision, not an engineering hygiene detail, and treating it as hygiene is how a team ends up with a 60 per cent output increase and nothing extra in production.",
      "## What a team is actually short of",
      "If building is cheap and checking is expensive, then the scarce skills are the ones that reduce how much checking is needed.",
      "Writing down what done means before anyone starts, in terms a person can verify without asking you. Killing the feature in the document instead of in review. Being clear enough about the edge cases that the diff does not surface eleven new questions. Knowing which of those eleven questions actually matters.",
      "That list is a description of the job I have been doing under an engineering title. It is also, roughly, the job description for product management.",
      "## Where I should declare my bias",
      "I am an engineer moving into product roles, and I have just argued that product judgement is the scarce resource. That is a convenient conclusion for me to reach and you should weigh it accordingly.",
      "What I would say in my defence is that I arrived at it from the wrong direction. I did not decide to move into product and then look for a trend that justified it. I noticed that the half of my week which got dramatically faster was the half I thought was the valuable one, and that the half that did not budge was the half I had been treating as overhead.",
      "## What I would measure",
      "Not lines of code and not commits, both of which now measure how fast a model types. Time from pull request opened to merged, which is where the queue actually is. What share of generated changes are merged without substantial rework. How many questions a review surfaces that a decent specification would have answered first.",
      "And the one I would put on the wall: how much of what shipped this quarter, anybody uses.",
    ],
  },
  {
    title: "How to write a PRD for a feature that can be wrong",
    outlet: "Space OS",
    date: "2026-09-23",
    slug: "prd-for-an-ai-feature",
    href: "/writing/prd-for-an-ai-feature",
    status: "published",
    kind: "essay",
    line: "A PRD works because software is deterministic. A model is not. What acceptance criteria become when the same input can produce a different answer on Tuesday.",
    related: { label: "How I approach PRDs as an engineer", href: "/writing/prds-as-an-engineer" },
    body: [
      "Every PRD I have written assumes something nobody bothers to say out loud: the same input gives you the same output. You write down what has to happen, someone builds it, someone else checks it, and the thing behaves on Tuesday the way it behaved on Monday. Put a model in the middle and that stops being true. The document has to change shape, and skipping that is how AI features get shipped without anyone being able to say whether they work.",
      "## The criteria that stop working",
      "“The summary is accurate.” “The assistant answers the question.” “Suggestions are relevant.” None of those is testable. Two reasonable people will look at the same output and disagree about whether it passed.",
      "On the fleet dashboards I could write “within 400ms the marker turns amber” and hand it to a tester who never had to ask me a follow-up question. That is the bar. A criterion you have to interpret is not a criterion, it is a preference you wrote down.",
      "## What goes in instead",
      "You stop writing statements and start collecting cases. Thirty real inputs: the boring ones, the ones people actually send, and a handful you are nervous about. For each, what a good answer looks like and what an unacceptable one looks like.",
      "Then the criterion becomes a proportion plus a hard floor. Eighty per cent of the thirty have to be acceptable, and there is a smaller set that must never fail at all. “Nothing in the safety set produces an instruction that could damage a vehicle” is something a person can check on a Thursday. “The assistant is helpful” is not.",
      "Choosing those thirty inputs is the product decision. It is the same act as deciding what the feature is for, and I would not hand it to anyone else.",
      "## Wrong is a spectrum, so rank it",
      "Ordinary software fails loudly. The request errors, the screen goes blank, someone raises a ticket within the hour. Model-powered features fail softly. The answer looks fine, it is off by a bit, and nobody catches it for a month.",
      "So the document has to say which kinds of wrong you can live with. In fleet software that ordering is easy to write. An alert that fires when nothing happened costs an operator half a minute of annoyance. An alert that stays quiet while a vehicle sits in the wrong place for four hours costs a delivery, and sometimes a customer. Rolling both into one accuracy percentage throws away the only part of the analysis that mattered.",
      "## Edge cases are where knowing the system pays off",
      "This is the part that is easier when you have built things. On deterministic work it meant knowing that route playback breaks when the GPS data has a hole in it, that an alarm can fire twice, that a dashboard which is fine at a hundred vehicles falls over at ten thousand.",
      "The model version of that list: input arrives in a language nobody planned for. The retrieved context is three weeks stale. The model is confidently wrong in a way that reads well. The provider is slow at 4pm. Someone asks the same question twice, gets two different answers, and screenshots it.",
      "Write those down before the build, not after the demo.",
      "## Cost and latency belong in the PRD",
      "People file these under engineering. They are not. Eight seconds and eight hundred milliseconds are two different products; one of them can sit inside the workflow and the other has to sit beside it. And a feature that costs more per call than the work it replaces will get cancelled eventually, just after you have built the whole thing.",
      "I learned the general version of this at scale, where how fast the map drew decided what the operator could actually see. The budget shapes what the feature can be. That makes it a requirement.",
      "## What I would measure",
      "Not model accuracy. How often someone accepts the output without editing it. How often they act on what it suggested. How often they ask the same thing twice because the first answer was no use.",
      "And one I have not seen anyone track: how long it takes the team to notice when quality slips. It will slip, and it will not announce itself.",
    ],
  },
  {
    title: "An AI agent that acts is an alarm that fires",
    outlet: "Space OS",
    date: "2026-09-23",
    slug: "agents-and-the-alarm-problem",
    href: "/writing/agents-and-the-alarm-problem",
    status: "published",
    kind: "essay",
    line: "Plenty of enterprise agent pilots, far fewer agents in production. Fleet software solved a version of this problem years ago, and the lesson is not about the model.",
    related: { label: "The mission the alarms were built for", href: "/missions/control-tower" },
    body: [
      "Everyone is finding out this year that an agent which can act is not the same as an agent anyone lets act. The surveys all come out the same way. Lots of pilots, far fewer things actually running, and quality is the reason people give for the gap.",
      "I have built the version of this problem that existed before anyone said the word agent. Alert systems for vehicle fleets. It fails in a way I recognise.",
      "## The alarm problem",
      "Build something that detects conditions and it will detect them. A week in, the operator has three hundred notifications a day and four of them matter. By week three she is clearing the list without reading it. The system is now worse than having nothing, because everyone upstairs believes the fleet is being watched.",
      "Detection was never the difficult part. The difficult part is that an alert nobody acts on is noise, and noise teaches people to stop looking at whatever channel it comes through. Once that has happened you cannot undo it by improving the detection.",
      "An agent is the same thing with the stakes raised. It does not tell you about a condition, it does something about it. The equivalent of a dismissed alert is a colleague having to undo the action.",
      "## The handoff is the product",
      "On the telematics platforms we treated alarms, geofences and ticketing as one chain rather than three features. A geofence says what counts as the condition. An alarm says it happened. A ticket says who owns it now.",
      "That third link is the one that gets cut. It is the least interesting thing to specify and it is the only reason the first two are worth building.",
      "Most agents I have looked at ship with two links. It decides, it acts, and then the trail goes cold. No record of why, nobody named as responsible, no obvious route for a person who thinks it got this one wrong. Teams put observability in and call that covered, but knowing what the agent did tells you nothing about who answers for it.",
      "## Autonomy is a dial",
      "The question is never whether the agent can do the thing. It is what happens the tenth time it does the thing badly.",
      "Which makes autonomy a setting, and one that should be visible: suggest and wait, act and tell someone, act quietly and log it. Different actions inside the same product deserve different settings. The setting should be allowed to move once you have evidence, which means somebody has to be collecting the evidence, which is the step that gets skipped.",
      "Put it in fleet terms. Drafting a ticket is a suggestion. Closing one is an action. Sending a technician across the city is an action that costs diesel and somebody's afternoon. Nobody would give those three the same permissions, and yet software teams hand their agent one level for everything and then act surprised.",
      "## Trust gets withdrawn quietly",
      "I wrote a teardown a while back on why developers adopt AI coding assistants and then stop trusting them for the parts that matter, while carrying on using them for the parts that do not. Nobody raises a ticket to say they have lost confidence. The usage numbers stay healthy while the product hollows out underneath them.",
      "Agents will go the same way and the same dashboard will hide it. Seats and sessions look fine while every user quietly shrinks the list of things they will let it touch.",
      "## What I would measure",
      "How many of the actions it took got reversed by a person. How many of its suggestions were accepted without an edit. How wide the set of permissions a given user leaves it after three months, compared with the first week.",
      "And the one that carries over directly from fleet work: what share of alerts ended as a closed ticket rather than a dismissal. That number tells you whether you built a colleague or another notification.",
    ],
  },
  {
    title: "What AI actually changes in fleet software",
    outlet: "Space OS",
    date: "2026-09-23",
    slug: "ai-in-fleet-software",
    href: "/writing/ai-in-fleet-software",
    status: "published",
    kind: "essay",
    line: "Nobody watching two hundred thousand vehicles wants a chatbot. They want the product to notice the thing they would have found an hour later.",
    related: { label: "Vahan Shakti, the mission report", href: "/missions/vahan-shakti" },
    body: [
      "Every category is being told it needs AI and most of them are being shown the same demo, which is a chat box bolted to the corner of something that already exists. In fleet and telematics software, where I have spent the last two years, that demo does almost nothing. The version that would actually help is dull enough that nobody puts it in a launch video.",
      "## A chat box is the wrong shape for this job",
      "The operator watching a live map of thousands of vehicles is not short of ways to ask a question. She is short of attention.",
      "Everything worth building on those products took a step away from her. Rotating the map to the vehicle's heading so nobody has to translate north into left. Fitting a whole route into one view instead of hunting for it. Replaying a trip rather than reading a table of coordinates. A chat interface asks her to compose a query, wait, and read a paragraph. That is a step back in.",
      "## What would help is the product noticing first",
      "The useful thing is surfacing what she would have found an hour later anyway. The vehicle idling somewhere vehicles do not idle. The route deviation that is going to turn into a late delivery. The alarm that has fired eleven times this week and never meant anything.",
      "That work is ranking. Deciding what belongs at the top of a list currently sorted by time.",
      "Which is also where the risk sits, because ranking means something goes below the fold. A product that quietly buries the one alert that mattered has done more harm than the version that never ranked anything.",
      "## You need the states before you need the model",
      "None of it works until a vehicle is in exactly one of a known set of states. Moving, stopped, idle, delayed, offline. Five words, with the lines between them drawn once and in one place.",
      "Every team I have watched try something clever on top of location data runs into this early. The data says where a vehicle is. The product needs to say what it is doing. Until those five words mean one thing each across the map, the alerts, the trip views and the compliance reports, a model sitting on top has nothing stable to be right about.",
      "The prerequisite for AI in an operational product is a data model that somebody argued about for two weeks.",
      "## Where it already pays, without the label",
      "Three places, none of them exciting. Cutting alert volume so the remaining alerts get read. Turning free text in tickets into the structured fields nobody fills in by hand. And extraction, which is what I worked on before I got into fleet software, pulling numbers off documents that arrive as photographs of documents.",
      "That last one has been working quietly for years and has never needed a conversation interface.",
      "## The scale question",
      "At two hundred thousand vehicles, anything you run per vehicle you are running two hundred thousand times. Cost and latency stop being infrastructure concerns and start deciding what the feature can be, the same way rendering cost did. Clustering and lazy rendering were not visual preferences on those maps. Without them nothing was usable at all.",
      "Any AI feature in this category has that waiting for it. Better to find it in the requirements than in the first invoice.",
      "## What I would measure",
      "How long it takes an operator to find the one vehicle that needs her, before and after. What share of the things you surface end in an action instead of a dismissal.",
      "And the uncomfortable one: how often something that mattered got ranked below something that did not. If you are not measuring that, you have not really shipped a ranking feature.",
    ],
  },
  {
    title: "The AI product manager is four jobs, not one",
    outlet: "Space OS",
    date: "2026-09-21",
    slug: "ai-product-manager-four-jobs",
    href: "/writing/ai-product-manager-four-jobs",
    status: "published",
    kind: "essay",
    line: "What the 2026 market is actually hiring when it says “AI PM”, why the junior rung has gone missing, and what an engineer moving into product should read in a posting before applying.",
    related: { label: "A related teardown: the AI coding-assistant adoption paradox", href: "/field-notes/ai-code-assistant-adoption-paradox" },
    body: [
      "I am moving from building products to managing them, in a year when almost every product-management posting has “AI” somewhere in it. This is what I have worked out from reading a great many of them, from shipping software alongside models, and from being on the receiving end of the hiring funnel. It is a market note, not a career guide.",
      "## The title is one word; the work is four",
      "Read past the title and “AI product manager” resolves into four different jobs. The first owns a customer-facing assistant — a chat or copilot surface where the model is the product and the hard problems are trust, latency, and what to do when the answer is wrong. The second owns the platform underneath: models, evaluation, tooling, cost, for teams inside the company who will never talk to a customer. The third ships model-powered features inside a product that is not about AI at all — a smarter search, a summary, a suggestion — where the model is a means and the roadmap is still the roadmap. The fourth runs internal operations tooling, where the customer is a colleague and the metric is hours. These need different people. A posting that does not say which one it is has not finished its own PRD.",
      "## Why I care which one: fleet software is the third job already",
      "The telematics products I have worked on — a map of ten thousand vehicles, alarms, geofences, tickets — are exactly where the third kind of AI PM lands. Nobody wants a chatbot on top of a fleet dashboard. What an operator wants is for the product to notice the thing they would have noticed an hour later: the vehicle that has been idle in the wrong place, the route deviation that is going to become a delayed delivery, the alarm that is going to be noise. That is a model-powered feature inside a non-AI product, and everything I wrote about states, alarms and hand-offs still applies. The model does not replace the product decision about what a state means; it makes that decision more expensive to get wrong, because now it fires automatically.",
      "## The junior rung is missing",
      "The posting analyses I have read this year agree on one uncomfortable shape: the market is hiring at the manager level and above, and hardly at all below it. Companies want someone who has already owned an outcome, because a model in production is a live thing that can embarrass you, and nobody wants a first-timer holding it. I understand the logic and I think it is a mistake at the market level — it means the next generation of AI PMs is being recruited from people who are already PMs, and the people who understand how the systems actually behave, the engineers, are being told to come back in three years. That is the gap I am applying into, and the argument I make is the one this site makes: I have written the PRDs and then built what they said, at fleet scale, and I know which edge cases are real because I have hit them.",
      "## What “AI experience” should mean in a posting, and usually does not",
      "It should not mean “has used ChatGPT”. Three things I would look for in a candidate if I were writing the posting, and therefore three things I try to show. One: can you write an evaluation before you write a feature — what does a good answer look like, how will you know, what is the failure you refuse to ship with. Two: can you reason about cost and latency as product constraints, the way a fleet PM reasons about rendering ten thousand markers — the constraint changes what the feature can be. Three: have you watched real people use a model-powered feature and changed the feature because of it. The teardown I wrote on why developers adopt AI coding assistants and then quietly stop trusting them is that third thing done from the outside; doing it from the inside is the job.",
      "## What is going on in the market, plainly",
      "The AI premium in pay is real and it is pulling every generalist posting toward the label, whether or not the role has a model in it. Specialisation is winning: “growth PM”, “platform PM”, “AI PM” are replacing “product manager”, and a generalist résumé reads as unfinished. Enterprises that had no AI a year ago are hiring their first AI PM and do not yet know which of the four jobs they mean, so the first hire ends up defining the role — which is a good place to be if you can write the document. And the tooling for the job itself is changing under everyone: a PM who can prototype with a model, run an evaluation and read the logs is doing in an afternoon what used to be a two-week ask to an engineering team. That is the one place where coming from engineering is not a detour into product management but a head start.",
      "## What I would measure",
      "For the market: how many “AI PM” postings say which of the four jobs they are, six months from now. For myself: whether the next product I ship makes a model’s decision visible enough that an operator can disagree with it. A feature that fires and cannot be argued with is an alarm nobody acts on, with better marketing.",
    ],
  },
  {
    title: "UX decisions in real-time vehicle tracking",
    outlet: "Space OS",
    date: "2026-09-21",
    slug: "ux-decisions-in-vehicle-tracking",
    href: "/writing/ux-decisions-in-vehicle-tracking",
    status: "published",
    kind: "essay",
    line: "Five states, a map that turns, a route you can replay: the decisions that made a fleet product usable for the people watching ten thousand vehicles.",
    related: { label: "Vahan Shakti, the mission report", href: "/missions/vahan-shakti" },
    body: [
      "A vehicle-tracking product looks like a map with dots on it. The dots are the easy part. The product is every decision about what a dot means, when it changes, and what a person watching ten thousand of them is supposed to do next. These are the decisions I made on the fleet and telematics platforms at MapMyIndia, and why.",
      "## A vehicle is in one of five states, and the product says which",
      "Moving, stopped, idle, delayed, offline. Before those five were defined, a dot was just a position with a timestamp, and every screen interpreted it differently. Defining the states once — and drawing the line between “stopped” and “idle”, between “idle” and “offline” — gave the map, the alerts, the trip views and the compliance reports one vocabulary. An operator who learns it on the map recognises it in the alarm list. Most of the hard questions in the product were really questions about where those lines sit, and having them in one place means the question gets answered once.",
      "## The map turns with the vehicle, not the other way round",
      "Rotation, fit-to-route and route playback sound like map features. They are attention features. Rotating the map to the heading means the operator does not translate “north” into “left”; fit-to-route means one action shows the whole trip instead of a hunt across the screen; playback means a dispute about where a vehicle was at 14:20 is settled by watching, not by reading a table. Each one removes a step a human was doing in their head, and at fleet scale those steps are the whole day.",
      "## Alarms, geofences and tickets are one workflow, not three features",
      "An alarm nobody acts on is noise. The alarm, geofence and ticketing workflows were designed as one chain: a geofence defines the condition, an alarm says it happened, a ticket says who owns it now. Splitting them into three separate features — which is how they arrive in a requirements list — produces alerts that fire and go nowhere. Designing the hand-off between them is the product work.",
      "## Ten thousand dots is a rendering problem before it is a UX problem",
      "Vahan Shakti draws live positions for a very large fleet; Intouch is optimised for ten thousand active vehicles with headroom to fifty thousand. At those numbers the map cannot draw every marker every second. Clustering, heatmaps and custom markers are not visual flourishes — they are what makes the screen readable at all, and they change what an operator can see: patterns instead of pins. The same is true under the hood: the ~40% improvement on the data-heavy dashboards came from caching, RxJS state management and API optimisation, and a dashboard that renders in time is a UX decision as much as an engineering one.",
      "## What I would still measure",
      "How long an operator takes to find one vehicle in a fleet of thousands; how many alarms end as closed tickets rather than dismissed noise; how often route playback settles a dispute. The product exists to shorten the first and raise the second. Those are the numbers I would put in front of the next version.",
    ],
  },
  {
    title: "Fewer codes: the product standard behind DumbMoney",
    outlet: "Space OS",
    date: "2026-09-23",
    slug: "fewer-codes-dumbmoney",
    href: "/writing/fewer-codes-dumbmoney",
    status: "draft",
    kind: "essay",
    line: "Why a coupon site should carry fewer codes than its competitors, and what it costs to keep that promise.",
    related: { label: "DumbMoney, the venture", href: "/dumbmoney" },
    body: [
      "Every coupon site competes on the same number: how many codes it lists. DumbMoney is built on the opposite standard — a code that works — and this is the reasoning behind it, as its founder and CPO.",
      "## The incentive problem",
      "A coupon site earns when a shopper clicks through to a store. It does not earn less when the code fails at checkout. So the rational thing for a coupon site to do is list everything, forever, and let the shopper discover which codes are dead. The shopper pays for that with three failed attempts at checkout; the site pays nothing. The product decision at DumbMoney was to take that cost onto ourselves.",
      "## What “verified” has to mean",
      "It cannot mean “we scraped it recently”. On DumbMoney a code goes through automated checks first — expiry, duplicates — and then a person reads it before it goes live. Every published coupon carries the name of the founder who checked it. That last part matters more than it sounds: a name next to a code is a promise a specific person made, and it changes how carefully the checking is done.",
      "## Saying what you do not yet do",
      "The about page says plainly that not every code is yet manually tested at checkout. That sentence belongs on the site. A product that describes its own limit is easier to trust than one that claims perfection, and it gives the team a standard to work toward that users can hold us to.",
      "## Fewer, browsable, no signup",
      "The catalogue is organised by store and by category, the code is copied in one action, and nothing asks the shopper to create an account first. Each of those is a decision to remove a step between a person and a working discount. A signup wall would raise a number we could report; it would also make the product worse at the one thing it is for.",
      "## What I would measure",
      "Of the codes people copy, how many work at checkout. That is the whole product in one number. Deals live, brands covered and repeat visits are worth tracking, but each of them is a proxy for the first.",
    ],
  },
  {
    title: "How I approach PRDs as an engineer",
    outlet: "Space OS",
    date: "2026-09-21",
    slug: "prds-as-an-engineer",
    href: "/writing/prds-as-an-engineer",
    status: "published",
    kind: "essay",
    line: "Writing the document and then building what it says: what changes in a PRD when the author is also the one who ships it.",
    related: { label: "The missions the PRDs were for", href: "/missions" },
    body: [
      "Most product requirement documents are written by someone who will not build the thing, for someone who will not decide what it is. I write mine from the other side of the table: at MapMyIndia I author the PRD and then I am one of the people who implements it. That changes what goes in the document, and what stays out.",
      "## Start with the problem, and write it down before the screens",
      "Every PRD I write opens with a problem statement, not a feature. The Mappls Shop Admin work is the clearest example: the problem was a fully manual billing process, and the document said so in one sentence before it said anything about an admin panel. A feature list without that sentence is a wish list; with it, every later argument about scope has something to argue against.",
      "## User stories are how you find the states you forgot",
      "I write user stories not because a template asks for them but because they force the states out. In fleet software, the interesting question is never the happy path — a vehicle is moving. It is what the product does when a vehicle is stopped, idle, delayed or offline, and who needs to know which. On the telematics platforms those five states became the vocabulary for the whole product: the map, the alerts, the compliance views. The stories surfaced them; the screens came after.",
      "## Acceptance criteria are a contract with your future self",
      "When the person writing the criteria will also be the person tested against them, the criteria get honest fast. Vague criteria do not survive contact with a Tuesday afternoon build. I write them as things a tester could check without asking me: what appears, what does not, within how long, and what happens on the failure path.",
      "## Edge cases are where the engineering knowledge earns its place",
      "This is the part an engineer can do that a pure spec-writer often cannot: knowing which edge cases are real. The kind of thing I mean — a route playback with a gap in the GPS data; an alarm that can fire twice; a dashboard that is fine at a hundred vehicles and unusable at ten thousand. Writing these into the PRD up front is cheaper than discovering them in a demo.",
      "## What stays out",
      "Implementation. The PRD says what the system must insist on and what it must never do; it does not say which library. That boundary is harder to hold when you are also the implementer, and holding it is most of the discipline. The document is for the people who have to agree on the problem — the operations team, the client, the other engineers — and the moment it starts describing the code, they stop reading.",
      "## Then ship, then look",
      "The loop I work in is problem → understand → strategy → UX → build → ship → learn → next problem. The PRD is the artefact of the first three steps. Its real test is the last one: after shipping, does the document still describe what the product does? When it does not, the gap is the next PRD.",
    ],
  },
  {
    title: "How to Use Coupons During Big Billion Days & Great Indian Festival",
    outlet: "DumbMoney",
    date: "2026-09-15",
    href: "https://dumbmoney.in/blog/how-to-use-coupons-big-billion-days-great-indian-festival",
    line: "A shopper's guide to the two biggest sale weeks of the Indian year, and how to use a coupon during them.",
    kind: "guide",
    related: { label: "DumbMoney, the venture", href: "/dumbmoney" },
  },
  {
    title: "Why Coupon Codes Stop Working (And How to Avoid Expired Ones)",
    outlet: "DumbMoney",
    date: "2026-09-10",
    href: "https://dumbmoney.in/blog/why-coupon-codes-stop-working",
    line: "Why a code fails at checkout, and how to avoid the expired ones.",
    kind: "essay",
    related: { label: "DumbMoney, the venture", href: "/dumbmoney" },
  },
  {
    title: "Cosmic Orange and the New “Pro”: A Case Study in Color-Led Strategy, Personas, and Accessible UX",
    outlet: "Medium",
    date: "2025-09-12",
    href: "https://medium.com/@aliazamkazmi1291/cosmic-orange-and-the-new-pro-a-case-study-in-color-led-strategy-personas-and-accessible-ux-54bfa3b86d6b",
    line: "A colour as product strategy: how one finish turns “Pro” into a visible signal, and what that asks of accessibility.",
    kind: "case study",
    related: { label: "More teardowns: the field notes", href: "/field-notes" },
  },
  {
    title: "No-Code vs. Custom Coding: What’s Best for Small Businesses in 2025?",
    outlet: "Medium",
    date: "2025-02-21",
    href: "https://medium.com/@aliazamkazmi1291/no-code-vs-custom-coding-whats-best-for-small-businesses-in-2025-7da9b8958d1c",
    line: "The build-or-buy call for a small business: when a no-code platform is the right product decision, and when it stops being one.",
    kind: "essay",
  },
  {
    title: "Understanding Middleware: The Backbone of Modern Software Systems",
    outlet: "Medium",
    date: "2024-11-25",
    href: "https://medium.com/@aliazamkazmi1291/understanding-middleware-the-backbone-of-modern-software-systems-854d5b677ceb",
    line: "The layer between systems that nobody sees and everything depends on, explained for people who ship on top of it.",
    kind: "essay",
  },
  {
    title: "Frontend Development Roadmap: A Comprehensive Guide",
    outlet: "Medium",
    date: "2024-09-30",
    href: "https://medium.com/@aliazamkazmi1291/frontend-development-roadmap-a-comprehensive-guide-8434644228d3",
    line: "A structured route through frontend engineering, from the fundamentals to the tooling that changes every year.",
    kind: "guide",
    related: { label: "The stack in use: the missions", href: "/missions" },
  },
  {
    title: "The Art of Balancing Aesthetics and Functionality: UI Design and Coding",
    outlet: "Medium",
    date: "2024-09-25",
    href: "https://medium.com/@aliazamkazmi1291/the-art-of-balancing-aesthetics-and-functionality-understanding-the-differences-between-ui-design-1ace225629d5",
    line: "Where UI and UX are not the same job, and what changes when the designer is also the one writing the code.",
    kind: "essay",
    related: { label: "The design work: Smaak.ux", href: "/studio" },
  },
];

/** Pieces written and hosted here. */
export const hostedWriting = writing.filter((p) => p.outlet === "Space OS" && p.slug && p.body);

/** Live means published, or any draft while developing (never a draft in production). */
export function isLive(p: Piece) {
  return p.status === "published" || (p.status === "draft" && process.env.NODE_ENV !== "production");
}

/**
 * The reverse of `related` (2026-09-23): given a mission, note or venture
 * path, which live pieces point at it. Essays linked INTO the work and
 * nothing linked back out, so a reader on a mission report had no route to
 * the writing about it — and a week of analytics showed /writing missing
 * from the top pages entirely.
 */
export function writingAbout(href: string): Piece[] {
  return writing.filter((p) => p.related?.href === href && (p.outlet !== "Space OS" || isLive(p)));
}

/** What the /writing log lists: everything external, plus hosted pieces that are live. */
export const listedWriting = writing.filter((p) => p.outlet !== "Space OS" || isLive(p));
